### PR TITLE
Fast forward to upstream v0.25.1

### PR DESCRIPTION
**Pull request by jrvaldes**
Ran:

```
git remote add upstream git@github.com:prometheus-community/windows_exporter.git

git fetch upstream

git merge v0.25.1
```

### CODE REVIEW

**Comment by jrvaldes** [comment]
/test build

bump 1.21 PR merged:
- https://github.com/openshift/release/pull/52173

**Comment by mansikulkarni96** [comment]
Thanks for opening this!
/approve

**Pull request merged**
