### PR TITLE
Bump to upstream v0.21.0

### PR DESCRIPTION
**Pull request by mansikulkarni96**
Ran commands:

git remote add upstream [git@github.com](mailto:git@github.com):prometheus-community/windows_exporter.git

git fetch upstream

git checkout -b pull-v0.21.0

git merge v0.21.0

go mod tidy && go mod vendor

### CODE REVIEW

**Comment by aravindhp** [comment]
@mansikulkarni96 Why do we see this https://github.com/openshift/prometheus-community-windows_exporter/pull/28/commits/ecdb67bc188fdfb56371b23c413bd8db047f3020 merge commit? This should not be there. I don't see it in the older PRs.

**Comment by mansikulkarni96** [comment]
@aravindhp That's right, updated now. PTAL when you get a chance.

**Comment by aravindhp** [comment]
I would like another pair of eyes on this. @saifshaikh48 @sebsoto please review.

**Comment by mansikulkarni96** [comment]
@aravindhp please merge when you get a chance.

**Pull request merged**
